[cmake]
version = "3.15"
cmkr-include = "cmake/cmkr.cmake"

[project]
name = "bncsutil"
version = "${VERSION}"
languages = ["C", "CXX"]
include-before = [
    "cmake/version.cmake",
]
include-after = [
    "cmake/generate.cmake",
]

[vcpkg]
version = "2022.07.25"
packages = ["mpir", "doctest"]

[find-package]
doctest = {}

[target.bncsutil]
type = "static"
sources = [
    "src/*.cpp",
    "src/*.c",
    "cmake/libinfo.h.in",
]
include-directories = [
    "$<BUILD_INTERFACE:${CMAKE_SOURCE_DIR}/include>",
    "$<INSTALL_INTERFACE:include>",
]
include-before = ["cmake/mpir.cmake"]
include-after = ["cmake/install.cmake"]
private-link-libraries = ["$<BUILD_INTERFACE:mpir>"]
private-compile-definitions = [
    "USE_NEW_BSHA1=${USE_NEW_BSHA1}",
    "BNCSUTIL_DEBUG_MESSAGES=${BNCSUTIL_DEBUG_MESSAGES}",
]

[target.test]
type = "executable"
sources = ["tests/*.cpp"]
link-libraries = ["doctest::doctest", "bncsutil"]
