[cmake]
version = "3.20.2"
cmkr-include = "cmake/cmkr.cmake"

[project]
name = "bncsutil"
version = "1.4.1"
languages = ["C", "CXX"]

[vcpkg]
version = "2022.07.25"
packages = [
    "mpir",
    "gtest",
]

[find-package]
GTest = {}

[target.bncsutil]
type = "static"
sources = [
    "src/*.cpp",
    "src/*.c",
]
include-directories = [
    "include",
]
include-before = ["cmake/mpir.cmake"]
link-libraries = ["mpir"]

[target.bncsutil-test]
type = "executable"
sources = [
    "test/*.cpp",
]
link-libraries = [
    "bncsutil",
    "GTest::gmock",
    "GTest::gtest",
    "GTest::gmock_main",
    "GTest::gtest_main",
]

[[install]]
targets = ["bncsutil"]
destination = "bin"