find_path(MPIR_INCLUDE_DIR "gmp.h" HINTS ${CURRENT_INSTALLED_DIR} PATH_SUFFIXES include)
if(NOT MPIR_INCLUDE_DIR)
    message(FATAL_ERROR "GMP includes not found")
endif()

find_library(MPIR_LIBRARIES_REL NAMES "${CMAKE_STATIC_LIBRARY_PREFIX}mpir${CMAKE_STATIC_LIBRARY_SUFFIX}" HINTS ${CURRENT_INSTALLED_DIR} PATH_SUFFIXES lib)
if(NOT MPIR_LIBRARIES_REL)
    message(FATAL_ERROR "mpir library not found")
endif()

add_library(mpir STATIC IMPORTED)
set_target_properties(mpir PROPERTIES
    IMPORTED_LOCATION "${MPIR_LIBRARIES_REL}"
    INTERFACE_INCLUDE_DIRECTORIES "${MPIR_INCLUDE_DIR}"
)
