name: CMake

on:
  push:
    branches:
      - feature/*

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        type: [ Debug ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install -y yasm texinfo

      - name: Caching vcpkg deps
        uses: actions/cache@v3
        with:
          path: |
            build/_deps
            build/vcpkg_installed
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-

      - name: Build
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.type }}
          cmake --build build --config ${{ matrix.type }} --parallel
          cmake --install build --prefix ./install --config ${{ matrix.type }}

      - name: Test
        run: |
          ./test
        working-directory: build

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-${{ matrix.os }}
          path: install/lib/*
