name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - '**/*.c'
      - '**/*.cpp'
      - '**/*.h'
      - '**/*.cmake'
      - 'CMakeLists.txt'
      - '.github/workflows/release.yml'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          extra_plugins: |
            @semantic-release/changelog@6.0.0
            @semantic-release/git@10.0.0
            conventional-changelog-conventionalcommits@4.6.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        release: [ Release ]
    runs-on: ${{ matrix.os }}
    needs:
      - release
    if: needs.release.outputs.new_release_published == 'true'

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install -y yasm texinfo

      - name: Caching vcpkg deps
        uses: actions/cache@v3
        with:
          path: |
            build/_deps
            build/vcpkg_installed
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-

      - name: Build
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.release }} -DWORKFLOW_PROVIDED_VERSION=${{ needs.release.outputs.new_release_version }}
          cmake --build build --config ${{ matrix.release }} --parallel
          cmake --install build --prefix ./install --config ${{ matrix.release }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-${{ matrix.os }}-${{ matrix.release }}
          path: install/lib/*

  upload:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        release: [ Release ]
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Download build artefacts
        uses: actions/download-artifact@v1
        with:
          name: ${{ github.event.repository.name }}-${{ matrix.os }}-${{ matrix.release }}
          path: install/lib/

      - name: Create release archive
        run: |
          mkdir release
          zip -uj release/${{ github.event.repository.name }}-${{ matrix.os }}-${{ matrix.release }}.zip install/*
          zip -uj release/${{ github.event.repository.name }}-${{ matrix.os }}-${{ matrix.release }}.zip include/*

      - name: Upload release assets
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: './release/*'
